# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created: Mon Mar 16 12:20:47 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(420, 430)
        Form.setStyleSheet(_fromUtf8("color: #333;"))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.size = QtGui.QWidget()
        self.size.setObjectName(_fromUtf8("size"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.size)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.size)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.size_sens = QtGui.QLineEdit(self.size)
        self.size_sens.setObjectName(_fromUtf8("size_sens"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.size_sens)
        self.label_3 = QtGui.QLabel(self.size)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.size_dpi = QtGui.QLineEdit(self.size)
        self.size_dpi.setObjectName(_fromUtf8("size_dpi"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.size_dpi)
        self.label_7 = QtGui.QLabel(self.size)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.size_zoom = QtGui.QLineEdit(self.size)
        self.size_zoom.setObjectName(_fromUtf8("size_zoom"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.size_zoom)
        self.size_rawinput = QtGui.QCheckBox(self.size)
        self.size_rawinput.setObjectName(_fromUtf8("size_rawinput"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.size_rawinput)
        self.label = QtGui.QLabel(self.size)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label)
        self.size_result_cm = QtGui.QLabel(self.size)
        self.size_result_cm.setObjectName(_fromUtf8("size_result_cm"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.size_result_cm)
        self.label_6 = QtGui.QLabel(self.size)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.size_result_in = QtGui.QLabel(self.size)
        self.size_result_in.setObjectName(_fromUtf8("size_result_in"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.size_result_in)
        self.label_8 = QtGui.QLabel(self.size)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_8)
        self.size_result_zoom_cm = QtGui.QLabel(self.size)
        self.size_result_zoom_cm.setObjectName(_fromUtf8("size_result_zoom_cm"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.size_result_zoom_cm)
        self.label_9 = QtGui.QLabel(self.size)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.size_result_zoom_in = QtGui.QLabel(self.size)
        self.size_result_zoom_in.setObjectName(_fromUtf8("size_result_zoom_in"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.size_result_zoom_in)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.frame_6 = QtGui.QFrame(self.size)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.size_copy = QtGui.QPushButton(self.frame_6)
        self.size_copy.setEnabled(True)
        self.size_copy.setObjectName(_fromUtf8("size_copy"))
        self.horizontalLayout_7.addWidget(self.size_copy)
        self.size_calculate = QtGui.QPushButton(self.frame_6)
        self.size_calculate.setMinimumSize(QtCore.QSize(0, 0))
        self.size_calculate.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.size_calculate.setObjectName(_fromUtf8("size_calculate"))
        self.horizontalLayout_7.addWidget(self.size_calculate)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.size, _fromUtf8(""))
        self.random = QtGui.QWidget()
        self.random.setObjectName(_fromUtf8("random"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.random)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_10 = QtGui.QLabel(self.random)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.random_dpi = QtGui.QLineEdit(self.random)
        self.random_dpi.setObjectName(_fromUtf8("random_dpi"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.random_dpi)
        self.random_check_type = QtGui.QCheckBox(self.random)
        self.random_check_type.setChecked(True)
        self.random_check_type.setObjectName(_fromUtf8("random_check_type"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.random_check_type)
        self.frame_5 = QtGui.QFrame(self.random)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.random_slider_type = QtGui.QSlider(self.frame_5)
        self.random_slider_type.setMinimum(1)
        self.random_slider_type.setMaximum(3)
        self.random_slider_type.setProperty("value", 2)
        self.random_slider_type.setOrientation(QtCore.Qt.Horizontal)
        self.random_slider_type.setObjectName(_fromUtf8("random_slider_type"))
        self.horizontalLayout_6.addWidget(self.random_slider_type)
        self.random_type = QtGui.QLabel(self.frame_5)
        self.random_type.setObjectName(_fromUtf8("random_type"))
        self.horizontalLayout_6.addWidget(self.random_type)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_5)
        self.label_15 = QtGui.QLabel(self.random)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.random_logitech = QtGui.QRadioButton(self.random)
        self.random_logitech.setChecked(True)
        self.random_logitech.setObjectName(_fromUtf8("random_logitech"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.random_logitech)
        self.random_razer = QtGui.QRadioButton(self.random)
        self.random_razer.setObjectName(_fromUtf8("random_razer"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.random_razer)
        self.random_zowie = QtGui.QRadioButton(self.random)
        self.random_zowie.setObjectName(_fromUtf8("random_zowie"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.random_zowie)
        self.line_2 = QtGui.QFrame(self.random)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.label_12 = QtGui.QLabel(self.random)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_12)
        self.random_gen_sens = QtGui.QLabel(self.random)
        self.random_gen_sens.setObjectName(_fromUtf8("random_gen_sens"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.random_gen_sens)
        self.label_11 = QtGui.QLabel(self.random)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_11)
        self.random_gen_dpi = QtGui.QLabel(self.random)
        self.random_gen_dpi.setObjectName(_fromUtf8("random_gen_dpi"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.random_gen_dpi)
        self.label_13 = QtGui.QLabel(self.random)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_13)
        self.random_gen_cm = QtGui.QLabel(self.random)
        self.random_gen_cm.setObjectName(_fromUtf8("random_gen_cm"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.random_gen_cm)
        self.label_14 = QtGui.QLabel(self.random)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_14)
        self.random_gen_in = QtGui.QLabel(self.random)
        self.random_gen_in.setObjectName(_fromUtf8("random_gen_in"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.FieldRole, self.random_gen_in)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.random_generate = QtGui.QPushButton(self.random)
        self.random_generate.setObjectName(_fromUtf8("random_generate"))
        self.verticalLayout_4.addWidget(self.random_generate)
        self.tabWidget.addTab(self.random, _fromUtf8(""))
        self.convert = QtGui.QWidget()
        self.convert.setObjectName(_fromUtf8("convert"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.convert)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_16 = QtGui.QLabel(self.convert)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.convert_dpi = QtGui.QLineEdit(self.convert)
        self.convert_dpi.setObjectName(_fromUtf8("convert_dpi"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.convert_dpi)
        self.label_17 = QtGui.QLabel(self.convert)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.convert_sens = QtGui.QLineEdit(self.convert)
        self.convert_sens.setObjectName(_fromUtf8("convert_sens"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.convert_sens)
        self.label_18 = QtGui.QLabel(self.convert)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.convert_new_dpi = QtGui.QLineEdit(self.convert)
        self.convert_new_dpi.setObjectName(_fromUtf8("convert_new_dpi"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.convert_new_dpi)
        self.convert_all = QtGui.QCheckBox(self.convert)
        self.convert_all.setObjectName(_fromUtf8("convert_all"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.convert_all)
        self.label_20 = QtGui.QLabel(self.convert)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.convert_logitech = QtGui.QRadioButton(self.convert)
        self.convert_logitech.setEnabled(False)
        self.convert_logitech.setChecked(True)
        self.convert_logitech.setObjectName(_fromUtf8("convert_logitech"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.convert_logitech)
        self.convert_zowie = QtGui.QRadioButton(self.convert)
        self.convert_zowie.setEnabled(False)
        self.convert_zowie.setObjectName(_fromUtf8("convert_zowie"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.convert_zowie)
        self.convert_razer = QtGui.QRadioButton(self.convert)
        self.convert_razer.setEnabled(False)
        self.convert_razer.setObjectName(_fromUtf8("convert_razer"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.convert_razer)
        self.label_19 = QtGui.QLabel(self.convert)
        self.label_19.setEnabled(True)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_19)
        self.convert_new_sens = QtGui.QLabel(self.convert)
        self.convert_new_sens.setObjectName(_fromUtf8("convert_new_sens"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.convert_new_sens)
        self.convert_list = QtGui.QTextEdit(self.convert)
        self.convert_list.setObjectName(_fromUtf8("convert_list"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.SpanningRole, self.convert_list)
        self.verticalLayout_5.addLayout(self.formLayout_4)
        self.convert_btn = QtGui.QPushButton(self.convert)
        self.convert_btn.setObjectName(_fromUtf8("convert_btn"))
        self.verticalLayout_5.addWidget(self.convert_btn)
        self.tabWidget.addTab(self.convert, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.size2sens_inch = QtGui.QLineEdit(self.frame)
        self.size2sens_inch.setObjectName(_fromUtf8("size2sens_inch"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.size2sens_inch)
        self.label_22 = QtGui.QLabel(self.frame)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.size2sens_cm = QtGui.QLineEdit(self.frame)
        self.size2sens_cm.setObjectName(_fromUtf8("size2sens_cm"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.size2sens_cm)
        self.label_23 = QtGui.QLabel(self.frame)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.size2sens_dpi = QtGui.QLineEdit(self.frame)
        self.size2sens_dpi.setEnabled(True)
        self.size2sens_dpi.setObjectName(_fromUtf8("size2sens_dpi"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.size2sens_dpi)
        self.label_27 = QtGui.QLabel(self.frame)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_27)
        self.size2sens_sens = QtGui.QLineEdit(self.frame)
        self.size2sens_sens.setEnabled(False)
        self.size2sens_sens.setObjectName(_fromUtf8("size2sens_sens"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.size2sens_sens)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.size2sens_btn_inch = QtGui.QPushButton(self.frame_2)
        self.size2sens_btn_inch.setObjectName(_fromUtf8("size2sens_btn_inch"))
        self.horizontalLayout_2.addWidget(self.size2sens_btn_inch)
        self.size2sens_btn_cm = QtGui.QPushButton(self.frame_2)
        self.size2sens_btn_cm.setObjectName(_fromUtf8("size2sens_btn_cm"))
        self.horizontalLayout_2.addWidget(self.size2sens_btn_cm)
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.frame_2)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.size2sens_btn_zoom_inch = QtGui.QPushButton(self.frame_3)
        self.size2sens_btn_zoom_inch.setEnabled(False)
        self.size2sens_btn_zoom_inch.setObjectName(_fromUtf8("size2sens_btn_zoom_inch"))
        self.horizontalLayout_3.addWidget(self.size2sens_btn_zoom_inch)
        self.size2sens_btn_zoom_cm = QtGui.QPushButton(self.frame_3)
        self.size2sens_btn_zoom_cm.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size2sens_btn_zoom_cm.sizePolicy().hasHeightForWidth())
        self.size2sens_btn_zoom_cm.setSizePolicy(sizePolicy)
        self.size2sens_btn_zoom_cm.setObjectName(_fromUtf8("size2sens_btn_zoom_cm"))
        self.horizontalLayout_3.addWidget(self.size2sens_btn_zoom_cm)
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.frame_3)
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_24)
        self.size2sens_result_sens = QtGui.QLabel(self.frame)
        self.size2sens_result_sens.setObjectName(_fromUtf8("size2sens_result_sens"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.size2sens_result_sens)
        self.label123213 = QtGui.QLabel(self.frame)
        self.label123213.setObjectName(_fromUtf8("label123213"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label123213)
        self.size2sens_result_inch = QtGui.QLabel(self.frame)
        self.size2sens_result_inch.setObjectName(_fromUtf8("size2sens_result_inch"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.size2sens_result_inch)
        self.label_26 = QtGui.QLabel(self.frame)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_26)
        self.size2sens_result_cm = QtGui.QLabel(self.frame)
        self.size2sens_result_cm.setObjectName(_fromUtf8("size2sens_result_cm"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.size2sens_result_cm)
        self.label_28 = QtGui.QLabel(self.frame)
        self.label_28.setEnabled(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_28)
        self.size2sens_result_zoom = QtGui.QLabel(self.frame)
        self.size2sens_result_zoom.setObjectName(_fromUtf8("size2sens_result_zoom"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.size2sens_result_zoom)
        self.verticalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.history_calendar = QtGui.QCalendarWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_calendar.sizePolicy().hasHeightForWidth())
        self.history_calendar.setSizePolicy(sizePolicy)
        self.history_calendar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.history_calendar.setGridVisible(True)
        self.history_calendar.setHorizontalHeaderFormat(QtGui.QCalendarWidget.ShortDayNames)
        self.history_calendar.setNavigationBarVisible(True)
        self.history_calendar.setDateEditEnabled(True)
        self.history_calendar.setObjectName(_fromUtf8("history_calendar"))
        self.verticalLayout_6.addWidget(self.history_calendar)
        self.frame_4 = QtGui.QFrame(self.widget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(274, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.history_show = QtGui.QPushButton(self.frame_4)
        self.history_show.setObjectName(_fromUtf8("history_show"))
        self.horizontalLayout_5.addWidget(self.history_show)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_29)
        self.frame_7 = QtGui.QFrame(self.groupBox)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_30 = QtGui.QLabel(self.frame_7)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_8.addWidget(self.label_30)
        self.settings_random_low_min = QtGui.QLineEdit(self.frame_7)
        self.settings_random_low_min.setObjectName(_fromUtf8("settings_random_low_min"))
        self.horizontalLayout_8.addWidget(self.settings_random_low_min)
        self.label_31 = QtGui.QLabel(self.frame_7)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_8.addWidget(self.label_31)
        self.settings_random_low_max = QtGui.QLineEdit(self.frame_7)
        self.settings_random_low_max.setObjectName(_fromUtf8("settings_random_low_max"))
        self.horizontalLayout_8.addWidget(self.settings_random_low_max)
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_7)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.frame_8 = QtGui.QFrame(self.groupBox)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_33 = QtGui.QLabel(self.frame_8)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_9.addWidget(self.label_33)
        self.settings_random_medium_min = QtGui.QLineEdit(self.frame_8)
        self.settings_random_medium_min.setObjectName(_fromUtf8("settings_random_medium_min"))
        self.horizontalLayout_9.addWidget(self.settings_random_medium_min)
        self.label_34 = QtGui.QLabel(self.frame_8)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_9.addWidget(self.label_34)
        self.settings_random_medium_max = QtGui.QLineEdit(self.frame_8)
        self.settings_random_medium_max.setObjectName(_fromUtf8("settings_random_medium_max"))
        self.horizontalLayout_9.addWidget(self.settings_random_medium_max)
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_8)
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_35)
        self.frame_9 = QtGui.QFrame(self.groupBox)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_36 = QtGui.QLabel(self.frame_9)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_10.addWidget(self.label_36)
        self.settings_random_high_min = QtGui.QLineEdit(self.frame_9)
        self.settings_random_high_min.setObjectName(_fromUtf8("settings_random_high_min"))
        self.horizontalLayout_10.addWidget(self.settings_random_high_min)
        self.label_37 = QtGui.QLabel(self.frame_9)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_10.addWidget(self.label_37)
        self.settings_random_high_max = QtGui.QLineEdit(self.frame_9)
        self.settings_random_high_max.setObjectName(_fromUtf8("settings_random_high_max"))
        self.horizontalLayout_10.addWidget(self.settings_random_high_max)
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_9)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_38)
        self.frame_11 = QtGui.QFrame(self.groupBox)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_39 = QtGui.QLabel(self.frame_11)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_12.addWidget(self.label_39)
        self.settings_random_all_min = QtGui.QLineEdit(self.frame_11)
        self.settings_random_all_min.setObjectName(_fromUtf8("settings_random_all_min"))
        self.horizontalLayout_12.addWidget(self.settings_random_all_min)
        self.label_40 = QtGui.QLabel(self.frame_11)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_12.addWidget(self.label_40)
        self.settings_random_all_max = QtGui.QLineEdit(self.frame_11)
        self.settings_random_all_max.setObjectName(_fromUtf8("settings_random_all_max"))
        self.horizontalLayout_12.addWidget(self.settings_random_all_max)
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.frame_11)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_41)
        self.settings_m_yaw = QtGui.QLineEdit(self.groupBox_2)
        self.settings_m_yaw.setObjectName(_fromUtf8("settings_m_yaw"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.settings_m_yaw)
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_42)
        self.frame_12 = QtGui.QFrame(self.groupBox_2)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.size_win_sens = QtGui.QSlider(self.frame_12)
        self.size_win_sens.setMinimum(1)
        self.size_win_sens.setMaximum(11)
        self.size_win_sens.setProperty("value", 6)
        self.size_win_sens.setOrientation(QtCore.Qt.Horizontal)
        self.size_win_sens.setObjectName(_fromUtf8("size_win_sens"))
        self.horizontalLayout_13.addWidget(self.size_win_sens)
        self.size_label_win = QtGui.QLabel(self.frame_12)
        self.size_label_win.setObjectName(_fromUtf8("size_label_win"))
        self.horizontalLayout_13.addWidget(self.size_label_win)
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_12)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.frame_10 = QtGui.QFrame(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.settings_label = QtGui.QLabel(self.frame_10)
        self.settings_label.setEnabled(True)
        self.settings_label.setAutoFillBackground(False)
        self.settings_label.setStyleSheet(_fromUtf8("color: #2ecc71;\n"
"font-weight: bold;"))
        self.settings_label.setObjectName(_fromUtf8("settings_label"))
        self.horizontalLayout_11.addWidget(self.settings_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.settings_btn_save = QtGui.QPushButton(self.frame_10)
        self.settings_btn_save.setMaximumSize(QtCore.QSize(80, 16777215))
        self.settings_btn_save.setMouseTracking(False)
        self.settings_btn_save.setObjectName(_fromUtf8("settings_btn_save"))
        self.horizontalLayout_11.addWidget(self.settings_btn_save)
        self.verticalLayout_8.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget, QtCore.Qt.AlignTop)
        self.skillurl = QtGui.QPushButton(Form)
        self.skillurl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.skillurl.setAutoFillBackground(False)
        self.skillurl.setStyleSheet(_fromUtf8("background: transparent;\n"
"color: rgb(0, 68, 255);"))
        self.skillurl.setObjectName(_fromUtf8("skillurl"))
        self.verticalLayout.addWidget(self.skillurl)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Sensitivity Tools", None))
        self.label_2.setText(_translate("Form", "Game Sensitivity", None))
        self.label_3.setText(_translate("Form", "Mouse DPI", None))
        self.label_7.setText(_translate("Form", "zoom_sensitivity_ratio", None))
        self.size_zoom.setText(_translate("Form", "1", None))
        self.size_rawinput.setToolTip(_translate("Form", "will reset windows sensitivity to 6/11", None))
        self.size_rawinput.setText(_translate("Form", "m_rawinput", None))
        self.label.setText(_translate("Form", "cm/360:", None))
        self.size_result_cm.setText(_translate("Form", "0", None))
        self.label_6.setText(_translate("Form", "in/360:", None))
        self.size_result_in.setText(_translate("Form", "0", None))
        self.label_8.setText(_translate("Form", "zoom cm/360:", None))
        self.size_result_zoom_cm.setText(_translate("Form", "0", None))
        self.label_9.setText(_translate("Form", "zoom in/360:", None))
        self.size_result_zoom_in.setText(_translate("Form", "0", None))
        self.size_copy.setText(_translate("Form", "Copy info", None))
        self.size_calculate.setText(_translate("Form", "Calculate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.size), _translate("Form", "size/360", None))
        self.label_10.setText(_translate("Form", "Mouse DPI", None))
        self.random_check_type.setText(_translate("Form", "Type:", None))
        self.random_type.setText(_translate("Form", "Medium", None))
        self.label_15.setText(_translate("Form", "Mouse:", None))
        self.random_logitech.setText(_translate("Form", "Logitech -> 400-4000 DPI", None))
        self.random_razer.setText(_translate("Form", "Razer -> 400-6400 DPI", None))
        self.random_zowie.setText(_translate("Form", "Zowie -> 450 or 1150 or 2300 DPI", None))
        self.label_12.setText(_translate("Form", "Game Sensitivity:", None))
        self.random_gen_sens.setText(_translate("Form", "0", None))
        self.label_11.setText(_translate("Form", "Mouse DPI:", None))
        self.random_gen_dpi.setText(_translate("Form", "0", None))
        self.label_13.setText(_translate("Form", "cm/360:", None))
        self.random_gen_cm.setText(_translate("Form", "0", None))
        self.label_14.setText(_translate("Form", "in/360:", None))
        self.random_gen_in.setText(_translate("Form", "0", None))
        self.random_generate.setText(_translate("Form", "Generate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.random), _translate("Form", "Random", None))
        self.label_16.setText(_translate("Form", "DPI", None))
        self.label_17.setText(_translate("Form", "Sensitivity", None))
        self.label_18.setText(_translate("Form", "New DPI", None))
        self.convert_all.setToolTip(_translate("Form", "will show a list with all dpi available in certain mouse...", None))
        self.convert_all.setText(_translate("Form", "ALL DPIs", None))
        self.label_20.setText(_translate("Form", "Mouse:", None))
        self.convert_logitech.setText(_translate("Form", "Logitech\n"
"400-4000 DPI", None))
        self.convert_zowie.setText(_translate("Form", "Zowie -> 450,\n"
"1150 or 2300 DPI", None))
        self.convert_razer.setText(_translate("Form", "Razer\n"
"400-6400 DPI", None))
        self.label_19.setText(_translate("Form", "New Sensitivity:", None))
        self.convert_new_sens.setText(_translate("Form", "0", None))
        self.convert_btn.setText(_translate("Form", "Convert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.convert), _translate("Form", "Convert", None))
        self.label_21.setText(_translate("Form", "Inch/360:", None))
        self.label_22.setText(_translate("Form", "cm/360:", None))
        self.label_23.setText(_translate("Form", "DPI:", None))
        self.label_27.setText(_translate("Form", "Sens:", None))
        self.size2sens_btn_inch.setText(_translate("Form", "sens from inch", None))
        self.size2sens_btn_cm.setText(_translate("Form", "sens from cm", None))
        self.size2sens_btn_zoom_inch.setText(_translate("Form", "zoom from sens + inch", None))
        self.size2sens_btn_zoom_cm.setText(_translate("Form", "zoom from sens + cm", None))
        self.label_24.setText(_translate("Form", "Game Sens:", None))
        self.size2sens_result_sens.setText(_translate("Form", "0", None))
        self.label123213.setText(_translate("Form", "Inch/360:", None))
        self.size2sens_result_inch.setText(_translate("Form", "0", None))
        self.label_26.setText(_translate("Form", "cm/360:", None))
        self.size2sens_result_cm.setText(_translate("Form", "0", None))
        self.label_28.setText(_translate("Form", "zoom ratio:", None))
        self.size2sens_result_zoom.setText(_translate("Form", "1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "size2sens", None))
        self.history_show.setText(_translate("Form", "Show History", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "History", None))
        self.groupBox.setTitle(_translate("Form", "Random Sensitivity", None))
        self.label_29.setText(_translate("Form", "Low", None))
        self.label_30.setText(_translate("Form", "min:", None))
        self.label_31.setText(_translate("Form", "max:", None))
        self.label_32.setText(_translate("Form", "Medium", None))
        self.label_33.setText(_translate("Form", "min:", None))
        self.label_34.setText(_translate("Form", "max:", None))
        self.label_35.setText(_translate("Form", "High", None))
        self.label_36.setText(_translate("Form", "min:", None))
        self.label_37.setText(_translate("Form", "max:", None))
        self.label_38.setText(_translate("Form", "All", None))
        self.label_39.setText(_translate("Form", "min:", None))
        self.label_40.setText(_translate("Form", "max:", None))
        self.groupBox_2.setTitle(_translate("Form", "Sensitivity", None))
        self.label_41.setText(_translate("Form", "m_yaw", None))
        self.settings_m_yaw.setText(_translate("Form", "0.022", None))
        self.label_42.setText(_translate("Form", "Windows\n"
"Sensitivity", None))
        self.size_label_win.setText(_translate("Form", "6/11", None))
        self.settings_label.setText(_translate("Form", "Settings saved!", None))
        self.settings_btn_save.setText(_translate("Form", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Settings", None))
        self.skillurl.setText(_translate("Form", "http://github.com/sk1LLb0X", None))

